version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - farmatrack

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: farmatrack
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: farmatrack
      MYSQL_PASSWORD: secret
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - farmatrack

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - farmatrack

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - farmatrack

networks:
  farmatrack:
    driver: bridge

volumes:
  mysql-data:
    driver: local
